version: "3"
services:
  postgres:
    image: postgres:14
    container_name: tonyswan-db
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      PGDATA: /data/postgres
    ports: 
      -  "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes: 
      -  postgres:/data/postgres

volumes:
  postgres: