version: "3"
services:
  postgres:
    image: postgres:14
    container_name: tonyswan-db
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    ports: 
      -  "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes: 
      -  /path/to/local/data:/var/lib/postgresql/data
